#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_integer_dot_product : require

#define MMQ
#define B_TYPE block_q8_1_x4

#include "mul_mat_vec_base.glsl"

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

#if defined(DATA_A_QUANT_LEGACY) || defined(DATA_A_MXFP4)
#define K_PER_ITER 8
#elif defined(DATA_A_QUANT_K)
#define K_PER_ITER 16
#else
#error unimplemented
#endif

shared uint a_offset, b_offset, d_offset;

shared int32_t shared_b_qs[BLOCK_SIZE * (K_PER_ITER / 4)];
shared vec2 shared_b_ds[BLOCK_SIZE];

int32_t cache_b_qs[K_PER_ITER / 4];
vec2 cache_b_ds;

#include "mul_mat_vecq_funcs.glsl"

void iter(inout FLOAT_TYPE temp[NUM_COLS][NUM_ROWS], const uint first_row, const uint num_rows, const uint tid, const uint i) {
    [[unroll]] for (uint j = 0; j < NUM_COLS; ++j) {
        const uint col = i*BLOCK_SIZE + tid*K_PER_ITER;
        const uint b_block_idx = (j*p.batch_stride_b + col) / QUANT_K_Q8_1 + b_offset;
        const uint b_qs_idx = tid % (32 / K_PER_ITER);

        // Cooperative preload data_b block
        if (tid < gl_WorkGroupSize.x) {
            const uint b_block_idx_outer = b_block_idx / 4;
            const uint b_block_idx_inner = b_block_idx % 4;

            const B_TYPE b_block = data_b[b_block_idx_outer];
            shared_b_ds[tid] = vec2(b_block.ds[b_block_idx_inner]);

            const uint idx = tid * (K_PER_ITER / 4);
#if QUANT_R == 2
            const uint b_idx = b_block_idx_inner * 8 + b_qs_idx;

            // Assumes K_PER_ITER == 8
            shared_b_qs[idx    ] = b_block.qs[b_idx];
            shared_b_qs[idx + 1] = b_block.qs[b_idx + 4];
#else
            const uint b_idx = b_block_idx_inner * 8 + b_qs_idx * (K_PER_ITER / 4);
#if K_PER_ITER == 8
            shared_b_qs[idx    ] = b_block.qs[b_idx];
            shared_b_qs[idx + 1] = b_block.qs[b_idx + 1];
#elif K_PER_ITER == 16
            shared_b_qs[idx    ] = b_block.qs[b_idx];
            shared_b_qs[idx + 1] = b_block.qs[b_idx + 1];
            shared_b_qs[idx + 2] = b_block.qs[b_idx + 2];
            shared_b_qs[idx + 3] = b_block.qs[b_idx + 3];
#else
#error unimplemented
#endif
#endif
        }

        barrier();

        const uint idx = (tid % 32) * (K_PER_ITER / 4);
#if QUANT_R == 2
        cache_b_qs[0] = shared_b_qs[idx],
        cache_b_qs[1] = shared_b_qs[idx + 1],
#else
#if K_PER_ITER == 8
        cache_b_qs[0] = shared_b_qs[idx],
        cache_b_qs[1] = shared_b_qs[idx + 1],
#elif K_PER_ITER == 16
        cache_b_qs[0] = shared_b_qs[idx],
        cache_b_qs[1] = shared_b_qs[idx + 1],
        cache_b_qs[2] = shared_b_qs[idx + 2],
        cache_b_qs[3] = shared_b_qs[idx + 3],
#else
#error unimplemented
#endif
#endif

        cache_b_ds = shared_b_ds[tid % 32];

        uint ibi = first_row*p.ncols;
        [[unroll]] for (uint n = 0; n < num_rows; ++n) {
            const uint a_block_idx = (ibi + col)/QUANT_K_Q8_1 + a_offset;
            ibi += p.ncols;

            temp[j][n] += mmvq_dot_product(a_block_idx, b_qs_idx);
        }
    }
}

void compute_outputs(const uint32_t first_row, const uint32_t num_rows) {
    const uint tid = gl_LocalInvocationID.x;

    get_offsets(a_offset, b_offset, d_offset);
    a_offset /= QUANT_K_Q8_1;
    b_offset /= QUANT_K_Q8_1;

    FLOAT_TYPE temp[NUM_COLS][NUM_ROWS];

    [[unroll]] for (uint j = 0; j < NUM_COLS; ++j) {
        [[unroll]] for (uint n = 0; n < num_rows; ++n) {
            temp[j][n] = FLOAT_TYPE(0.0f);
        }
    }

    uint num_iters = p.ncols / (K_PER_ITER * BLOCK_SIZE);
    if (num_iters * K_PER_ITER * BLOCK_SIZE + K_PER_ITER*tid < p.ncols) {
        num_iters++;
    }
    int unroll_count = 4;
    uint unrolled_iters = num_iters & ~(unroll_count - 1);

    uint i = 0;
    while (i < unrolled_iters) {
        // Manually partially unroll the loop
        [[unroll]] for (uint k = 0; k < unroll_count; ++k) {
            iter(temp, first_row, num_rows, tid, i*K_PER_ITER);
            i++;
        }
    }

    unroll_count = 2;
    unrolled_iters = num_iters & ~(unroll_count - 1);

    while (i < unrolled_iters) {
        // Manually partially unroll the loop
        [[unroll]] for (uint k = 0; k < unroll_count; ++k) {
            iter(temp, first_row, num_rows, tid, i*K_PER_ITER);
            i++;
        }
    }
    while (i < num_iters) {
        iter(temp, first_row, num_rows, tid, i*K_PER_ITER);
        i++;
    }

    reduce_result(temp, d_offset, first_row, num_rows, tid);
}

void main() {
    const uint first_row = NUM_ROWS * (gl_WorkGroupID.x + gl_NumWorkGroups.x * gl_WorkGroupID.z);

#ifdef NEEDS_INIT_IQ_SHMEM
    init_iq_shmem(gl_WorkGroupSize);
#endif

    if (first_row >= p.stride_d) {
        return;
    }

    // do NUM_ROWS at a time, unless there aren't enough remaining rows
    const uint remaining_rows = p.stride_d - first_row;
    const uint num_rows = min(NUM_ROWS, remaining_rows);

    compute_outputs(first_row, num_rows);
}
